# Telepat.io Docker Compose file
# Author: Andrei Marinescu <andrei@telepat.io>
# Version 0.3.0
octopusapi:
  net: host
  image: telepat/octopusapi:0.4.4
  ports:
    - "3000:3000"
  command: ./bin/www

octopuswriter:
  net: host
  image: telepat/octopusworker:0.4.4
  command: node index.js -t write -i 0

octopusaggregator:
  net: host
  image: telepat/octopusworker:0.4.4
  command: node index.js -t aggregation -i 0

octopustransportmanager:
  net: host
  image: telepat/octopusworker:0.4.4
  command: node index.js -t transport_manager -i 0

octopusgcm:
  net: host
  image: telepat/octopusworker:0.4.4
  command: node index.js -t android_transport -i 0

octopusapns:
  net: host
  image: telepat/octopusworker:0.4.4
  command: node index.js -t ios_transport -i 0

octopusws:
  net: host
  image: telepat/octopusworker:0.4.4
  command: node index.js -t sockets_transport -i 0
